# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: Build

on:
  push:
    paths-ignore:
    - '**/*.md'
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2 #https://github.com/actions/checkout

    - name: Cache cygwin packages repository
      uses: actions/cache@v2
      with:
        path: cygwin\.pkg-cache
        key: ${{ runner.os }}-cygwinrepo

    - name: Install cygwin-portable
      shell: cmd
      run: call .\cygwin-portable-installer.cmd

    - name: Running cygwin-portable
      shell: cmd
      run: call .\cygwin-portable.cmd "bash --version"
